### ISSUE TITLE
ToDo before Sunday

### ISSUE THREAD

**Issue by systemaW** [Clueless-Aware/MauiFrontend#49]
Cose che faccio entro Domenica.

- [ ] Favoriti
- [ ] Integrazione Chat GPT
- [ ] Login UI (sottopagine comprese)
- [ ] Navbar fix
- [ ] Image Zoom per entrambi i result
- [ ] Give Images a fixed dimension in the results
- [ ] More info in the main results,  like time period and type of artwork
- [ ] Fix Ricerca admin con width troppo elevata
- [ ] Stile Uniforme dei pulsanti
