### ISSUE TITLE
Detail view for artwork

### ISSUE THREAD

**Issue by Aiuola** [Clueless-Aware/MauiFrontend#50]
It would be nice to have an accessible detail view for all users in the frontpage...

```[tasklist]
### Tasks
- [ ] Find a way to create an acnhor to the details page
- [ ] Find a way to pass parameters to this new view
- [ ] Display all the information in a nice way...
- [ ] OPTIONAL: Display some of the artist info
```

**Comment by Aiuola** [comment]
@RevenBot Update this issue...
