### ISSUE TITLE
Create Artist ViewModel and Pages

### ISSUE THREAD

**Issue by RevenBot** [Clueless-Aware/MauiFrontend#56]
```[tasklist]
### Tasks
- [x] Create new folders of artist and artworks pages
- [x] Create new dependency Scoped of Artist
- [x] Create viewModel of artist
- [x] Create basic page of search artist
- [x] Create add artist
- [x] Create admin search and edit
- [x] Create detail of artist
```
