### ISSUE TITLE
Rework the artwork and artist main page

### ISSUE THREAD

**Issue by RevenBot** [Clueless-Aware/MauiFrontend#58]
```[tasklist]
### Tasks
- [x] Create gallery on artwork main page
- [x] Adapt with paginator and search
- [x] Create anchor to detail page and presentation
- [x] Create gallery on artist main page
- [x] Adapt with paginator and search
- [x] Create anchor to detail page and presentation
```
