### ISSUE TITLE
Create a related artworks in detail view for artist/artwork

### ISSUE THREAD

**Issue by RevenBot** [Clueless-Aware/MauiFrontend#59]
```[tasklist]
### Tasks
- [x] Create new method in view model
- [x] Create a generic data in detail view
- [x] Create paginator in detail view
- [x] Create anchors to detail artists/artworks
```
