### ISSUE TITLE
Create search on add artwork

### ISSUE THREAD

**Issue by RevenBot** [Clueless-Aware/MauiFrontend#60]
```[tasklist]
### Tasks
- [ ] Create field search
- [ ] Create a method to search the artist
- [ ] On artist selected complete the fields author_id and author
```
