### ISSUE TITLE
Bugfix - Hotfix - Little Features

### ISSUE THREAD

**Issue by RevenBot** [Clueless-Aware/MauiFrontend#80]
```[tasklist]
### Tasks
- [x] Reduce related to 3 randoms
- [x] Add visit the museum (maps)
- [ ] Add google translate
- [x] Update the user on startup and edit user (refreshUserState)
- [ ] Close the app if there is no connection
```

**Comment by Aiuola** [comment]
RIPBOZO card di Angel

**Comment by RevenBot** [comment]
RIPBOZO BORDINO
